/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class TextAnalyzer extends javax.swing.JFrame {

    /**
     * Creates new form TextAnalyzer
     */
    public TextAnalyzer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        inputTextField = new javax.swing.JTextField();
        customInputCountTextField = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        linesTextField = new javax.swing.JTextField();
        spacesTextField = new javax.swing.JTextField();
        wordsTextField = new javax.swing.JTextField();
        tabsTextField = new javax.swing.JTextField();
        characterDropdown = new javax.swing.JComboBox<>();
        lengthTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTextArea.setColumns(20);
        mainTextArea.setRows(5);
        jScrollPane1.setViewportView(mainTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 380));

        jTextField1.setText("No. of spaces");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, 50));

        jTextField2.setText("No.  of Lines");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 50));

        jTextField3.setText("No. of words");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, 50));

        jTextField4.setText("Text Length");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 150, 50));

        jTextField5.setText("No. of Tabs");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 150, 50));

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 210, 40));

        inputTextField.setText("Input Text ");
        getContentPane().add(inputTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 110, 50));

        customInputCountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customInputCountTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customInputCountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 60, 50));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 50, 50));

        linesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linesTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(linesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 50, 50));
        getContentPane().add(spacesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 50, 50));
        getContentPane().add(wordsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, 50));
        getContentPane().add(tabsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 50, 50));

        characterDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        characterDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterDropdownActionPerformed(evt);
            }
        });
        getContentPane().add(characterDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 140, 40));
        getContentPane().add(lengthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 50, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TEXT ANALYZER ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void linesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linesTextFieldActionPerformed

    private void customInputCountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customInputCountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customInputCountTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String input = mainTextArea.getText();
        String customText = inputTextField.getText();
        
        int lineCount = 1;
        int spaceCount = 0;
        int wordCount = 0;
        int tabCount = 0;
        int textLength = input.length();
        int customTextCount = 0;
        
        String uniqueChars = "";
        boolean inWord = false;
        char ch = 0;
        for(int i = 0; i<input.length(); i++){
             ch = input.charAt(i);
        
        
        if(ch=='\n'){
            lineCount++;
        }
        
        else if(ch==' '){
            spaceCount++;
        }
        
        else if(ch=='\t'){
            tabCount++;
        }
        
        if(!Character.isWhitespace(ch) && uniqueChars.indexOf(ch)== -1){
            uniqueChars += ch;
        }
        
        if(Character.isWhitespace(ch)){
            if(inWord){
                wordCount++;
                inWord = false;
            }
        }
        else {
            inWord = true;
        }
        } 
        
        if(inWord) {
            wordCount++;
        }
        
        if (customText != null && !customText.isEmpty()) {
            int index = 0;
            while ((index = input.indexOf(customText, index)) != -1) {
                customTextCount++;
                index += customText.length();
            }
        }
        
        linesTextField.setText(String.valueOf(lineCount));
        spacesTextField.setText(String.valueOf(spaceCount));
        wordsTextField.setText(String.valueOf(wordCount));
        tabsTextField.setText(String.valueOf(tabCount));
        lengthTextField.setText(String.valueOf(textLength));
        customInputCountTextField.setText(String.valueOf(customTextCount));

        // Populate dropdown with unique characters
        characterDropdown.removeAllItems();
        for (int i = 0; i < uniqueChars.length(); i++) {
            characterDropdown.addItem(String.valueOf(uniqueChars.charAt(i)));
        }

        // Automatically count first character
        if (characterDropdown.getItemCount() > 0) {
            characterDropdown.setSelectedIndex(0);
            characterDropdownActionPerformed();
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void characterDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterDropdownActionPerformed
        // TODO add your handling code here:
        
     String input = mainTextArea.getText();
     String selected = (String)characterDropdown.getSelectedItem();
     
     if(selected != null && selected.length()==1){
         char ch = selected.charAt(0);
         int count = 0;
         
         for(int i =0; i<input.length(); i++){
             if(input.charAt(i) ==ch){
                 count++;
             }
         }
         
         jTextField9.setText(String.valueOf(count));
         
     }
     
     else{
         jTextField9.setText("0");
     }
    }//GEN-LAST:event_characterDropdownActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextAnalyzer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> characterDropdown;
    private javax.swing.JTextField customInputCountTextField;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JTextField linesTextField;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JTextField spacesTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tabsTextField;
    private javax.swing.JTextField wordsTextField;
    // End of variables declaration//GEN-END:variables

    private void characterDropdownActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
